"""File generation and writing module."""

from pathlib import Path
from typing import Dict, Optional
from utils.logger import get_logger
from utils.helpers import generate_project_id, ensure_directory, safe_write_file
from utils.errors import FileOperationException
from config.settings import settings

logger = get_logger(__name__)


class FileWriter:
    """Handle file generation and project structure creation."""

    # Default requirements for generated FastAPI projects
    DEFAULT_REQUIREMENTS = """fastapi==0.104.1
uvicorn[standard]==0.24.0
sqlalchemy==2.0.23
pydantic==2.5.0
python-dotenv==1.0.0
pydantic-settings==2.1.0
"""

    # Template for main.py
    MAIN_PY_TEMPLATE = '''"""
FastAPI application entry point.
Generated by AI-Powered API Builder
"""
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
import uvicorn

app = FastAPI(
    title="Generated API",
    description="API generated by AI-Powered API Builder",
    version="0.1.0",
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Import routes
# from routes import users, posts

# Include routers
# app.include_router(users.router)
# app.include_router(posts.router)

@app.get("/")
async def root():
    """Health check endpoint."""
    return {"message": "API is running"}

@app.get("/health")
async def health():
    """Health check endpoint."""
    return {"status": "healthy"}

if __name__ == "__main__":
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
    )
'''

    # Template for config
    CONFIG_TEMPLATE = '''"""
Configuration module.
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Project directories
BASE_DIR = Path(__file__).parent

# Database
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "sqlite:///./test.db"
)

# Application
DEBUG = os.getenv("DEBUG", "True").lower() == "true"
SECRET_KEY = os.getenv("SECRET_KEY", "your-secret-key-change-in-production")

# JWT
JWT_ALGORITHM = "HS256"
JWT_EXPIRATION_HOURS = 24
'''

    # Template for database
    DATABASE_TEMPLATE = '''"""
Database configuration and session management.
"""
from sqlalchemy import create_engine
from sqlalchemy.orm import declarative_base, sessionmaker
from config import DATABASE_URL

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if "sqlite" in DATABASE_URL else {}
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

Base = declarative_base()

def get_db():
    """Dependency to get database session."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
'''

    # Template for .env file
    ENV_TEMPLATE = '''# Database
DATABASE_URL=sqlite:///./test.db

# Application
DEBUG=true
SECRET_KEY=your-secret-key-here

# JWT
JWT_SECRET=your-jwt-secret-key

# Ollama (optional)
OLLAMA_BASE_URL=http://localhost:11434
'''

    @staticmethod
    def create_project_structure(
        project_id: Optional[str] = None,
        include_defaults: bool = True
    ) -> Path:
        """
        Create project directory structure.

        Args:
            project_id: Unique project ID (generated if not provided)
            include_defaults: Whether to create default files

        Returns:
            Path to created project directory

        Raises:
            FileOperationException: If creation fails
        """
        if not project_id:
            project_id = generate_project_id()

        project_dir = settings.GENERATED_PROJECTS_DIR / project_id

        try:
            ensure_directory(project_dir)

            # Create subdirectories
            ensure_directory(project_dir / "models")
            ensure_directory(project_dir / "routes")
            ensure_directory(project_dir / "schemas")
            ensure_directory(project_dir / "utils")

            logger.info(f"Created project structure at {project_dir}")

            # Create default files if requested
            if include_defaults:
                FileWriter._create_default_files(project_dir)

            return project_dir

        except Exception as e:
            logger.error(f"Failed to create project structure: {str(e)}")
            raise FileOperationException(f"Failed to create project: {str(e)}")

    @staticmethod
    def _create_default_files(project_dir: Path) -> None:
        """Create default template files."""
        try:
            # main.py
            safe_write_file(project_dir / "main.py", FileWriter.MAIN_PY_TEMPLATE)

            # config.py
            safe_write_file(project_dir / "config.py", FileWriter.CONFIG_TEMPLATE)

            # database.py
            safe_write_file(project_dir / "database.py", FileWriter.DATABASE_TEMPLATE)

            # .env
            safe_write_file(project_dir / ".env", FileWriter.ENV_TEMPLATE)

            # requirements.txt
            safe_write_file(project_dir / "requirements.txt", FileWriter.DEFAULT_REQUIREMENTS)

            # Create __init__.py files
            safe_write_file(project_dir / "models" / "__init__.py", "")
            safe_write_file(project_dir / "routes" / "__init__.py", "")
            safe_write_file(project_dir / "schemas" / "__init__.py", "")
            safe_write_file(project_dir / "utils" / "__init__.py", "")

            logger.info(f"Created default files in {project_dir}")

        except Exception as e:
            logger.error(f"Failed to create default files: {str(e)}")
            raise FileOperationException(f"Failed to create default files: {str(e)}")

    @staticmethod
    def write_file(
        project_dir: Path,
        filename: str,
        content: str,
        subdirectory: Optional[str] = None
    ) -> Path:
        """
        Write a file to the project directory.

        Args:
            project_dir: Project directory path
            filename: Name of the file
            content: File content
            subdirectory: Optional subdirectory within project

        Returns:
            Path to written file

        Raises:
            FileOperationException: If write fails
        """
        try:
            if subdirectory:
                filepath = project_dir / subdirectory / filename
            else:
                filepath = project_dir / filename

            safe_write_file(filepath, content)
            logger.info(f"Written file: {filepath}")
            return filepath

        except Exception as e:
            logger.error(f"Failed to write file {filename}: {str(e)}")
            raise FileOperationException(f"Failed to write file: {str(e)}")

    @staticmethod
    def write_code_blocks(
        project_dir: Path,
        code_blocks: Dict[str, "CodeBlock"]
    ) -> Dict[str, Path]:
        """
        Write multiple code blocks to files.

        Args:
            project_dir: Project directory path
            code_blocks: Dictionary of filename to CodeBlock

        Returns:
            Dictionary of filename to file path

        Raises:
            FileOperationException: If write fails
        """
        written_files = {}

        for filename, block in code_blocks.items():
            try:
                filepath = FileWriter.write_file(
                    project_dir,
                    filename,
                    block.content
                )
                written_files[filename] = filepath
            except FileOperationException as e:
                logger.error(f"Failed to write {filename}: {str(e)}")
                raise

        logger.info(f"Successfully wrote {len(written_files)} code blocks")
        return written_files

    @staticmethod
    def write_project_metadata(
        project_dir: Path,
        prompt: str,
        rules: Dict
    ) -> Path:
        """
        Write project metadata to a JSON file.

        Args:
            project_dir: Project directory path
            prompt: Original user prompt
            rules: Generation rules applied

        Returns:
            Path to metadata file
        """
        import json
        from datetime import datetime

        metadata = {
            "created_at": datetime.utcnow().isoformat(),
            "prompt": prompt,
            "rules": rules,
        }

        metadata_file = project_dir / ".project_metadata.json"
        safe_write_file(metadata_file, json.dumps(metadata, indent=2))

        logger.info(f"Written project metadata to {metadata_file}")
        return metadata_file

    @staticmethod
    def get_project_files(project_dir: Path) -> Dict[str, str]:
        """
        Get all Python files from a project directory.

        Args:
            project_dir: Project directory path

        Returns:
            Dictionary of filename to content
        """
        files = {}

        for py_file in project_dir.rglob("*.py"):
            # Skip __pycache__ and other cache directories
            if "__pycache__" in str(py_file):
                continue

            try:
                from utils.helpers import safe_read_file
                content = safe_read_file(py_file)
                relative_path = str(py_file.relative_to(project_dir))
                files[relative_path] = content
            except Exception as e:
                logger.warning(f"Could not read {py_file}: {str(e)}")

        return files

